-- Gerado por catalogo_base.mjs — 262 insumos · Rio de Janeiro · preços estimados (out/2026)
insert into public.catalogo_base (nome, sinonimos, categoria, unidade_compra, qtd_padrao, preco_medio, fator_aproveitamento, rendimento_preparo, regiao, origem_preco)
select v.nome, v.sinonimos, v.categoria, v.unidade_compra, v.qtd_padrao, v.preco_medio, v.fator_aproveitamento, v.rendimento_preparo, 'Rio de Janeiro', 'estimativa inicial'
from (values
  ('Picanha', array['picanha bovina']::text[], 'carne_bovina', 'kg', 1, 69.9, 85, 1),
  ('Contrafilé', array['contra filé','contra-filé','chorizo']::text[], 'carne_bovina', 'kg', 1, 46.9, 82, 1),
  ('Alcatra', array['miolo de alcatra']::text[], 'carne_bovina', 'kg', 1, 42.9, 85, 1),
  ('Filé mignon', array['file mignon','mignon']::text[], 'carne_bovina', 'kg', 1, 79.9, 80, 1),
  ('Patinho', array['patinho moído']::text[], 'carne_bovina', 'kg', 1, 38.9, 90, 1),
  ('Acém', array['acem']::text[], 'carne_bovina', 'kg', 1, 29.9, 85, 1),
  ('Músculo', array['musculo']::text[], 'carne_bovina', 'kg', 1, 31.9, 85, 1),
  ('Coxão mole', array['coxao mole','chã de dentro']::text[], 'carne_bovina', 'kg', 1, 39.9, 88, 1),
  ('Coxão duro', array['coxao duro','chã de fora']::text[], 'carne_bovina', 'kg', 1, 35.9, 88, 1),
  ('Fraldinha', array[]::text[], 'carne_bovina', 'kg', 1, 44.9, 85, 1),
  ('Maminha', array[]::text[], 'carne_bovina', 'kg', 1, 45.9, 88, 1),
  ('Costela bovina', array['costela de boi','costela']::text[], 'carne_bovina', 'kg', 1, 32.9, 60, 1),
  ('Cupim', array[]::text[], 'carne_bovina', 'kg', 1, 39.9, 80, 1),
  ('Carne moída', array['carne moida','moída de primeira']::text[], 'carne_bovina', 'kg', 1, 34.9, 92, 1),
  ('Blend de hambúrguer', array['blend','carne de hambúrguer','hamburguer bovino']::text[], 'carne_bovina', 'kg', 1, 36.9, 92, 1),
  ('Carne seca', array['carne de sol','jabá','charque']::text[], 'carne_bovina', 'kg', 1, 49.9, 75, 1),
  ('Bife ancho', array['ancho']::text[], 'carne_bovina', 'kg', 1, 74.9, 88, 1),
  ('Lagarto', array[]::text[], 'carne_bovina', 'kg', 1, 38.9, 90, 1),
  ('Lombo suíno', array['lombo de porco','lombo']::text[], 'carne_suina', 'kg', 1, 24.9, 90, 1),
  ('Pernil suíno', array['pernil']::text[], 'carne_suina', 'kg', 1, 19.9, 80, 1),
  ('Costelinha suína', array['costela de porco','costelinha']::text[], 'carne_suina', 'kg', 1, 27.9, 65, 1),
  ('Barriga suína', array['pancetta','barriga de porco']::text[], 'carne_suina', 'kg', 1, 26.9, 85, 1),
  ('Bisteca suína', array['bisteca']::text[], 'carne_suina', 'kg', 1, 21.9, 85, 1),
  ('Bacon', array['bacon em cubos','bacon fatiado']::text[], 'carne_suina', 'kg', 1, 34.9, 75, 1),
  ('Linguiça toscana', array['linguica toscana','linguiça de porco']::text[], 'carne_suina', 'kg', 1, 22.9, 85, 1),
  ('Linguiça calabresa', array['calabresa','linguica calabresa']::text[], 'carne_suina', 'kg', 1, 26.9, 90, 1),
  ('Presunto', array['presunto cozido','presunto fatiado']::text[], 'carne_suina', 'kg', 1, 29.9, 100, 1),
  ('Salame', array['salame italiano']::text[], 'carne_suina', 'kg', 1, 59.9, 100, 1),
  ('Pepperoni', array[]::text[], 'carne_suina', 'kg', 1, 54.9, 100, 1),
  ('Salsicha', array['salsicha hot dog']::text[], 'carne_suina', 'kg', 1, 16.9, 100, 1),
  ('Mortadela', array[]::text[], 'carne_suina', 'kg', 1, 19.9, 100, 1),
  ('Peito de peru', array['blanquet de peru','peru fatiado']::text[], 'aves', 'kg', 1, 44.9, 100, 1),
  ('Peito de frango', array['filé de frango','file de frango','frango peito']::text[], 'aves', 'kg', 1, 19.9, 90, 1),
  ('Coxa e sobrecoxa de frango', array['coxa de frango','sobrecoxa','coxa sobrecoxa']::text[], 'aves', 'kg', 1, 13.9, 70, 1),
  ('Frango inteiro', array['frango','frango congelado']::text[], 'aves', 'kg', 1, 11.9, 65, 1),
  ('Asa de frango', array['asinha','tulipa de frango','asa']::text[], 'aves', 'kg', 1, 16.9, 75, 1),
  ('Coração de frango', array['coracao de frango']::text[], 'aves', 'kg', 1, 24.9, 90, 1),
  ('Coxinha da asa', array['drumete']::text[], 'aves', 'kg', 1, 17.9, 75, 1),
  ('Frango desfiado cozido', array['frango desfiado']::text[], 'aves', 'kg', 1, 32.9, 100, 1),
  ('Salmão fresco', array['salmao','salmão','filé de salmão']::text[], 'peixes_frutos_mar', 'kg', 1, 79.9, 70, 1),
  ('Tilápia filé', array['tilapia','filé de tilápia','saint peter']::text[], 'peixes_frutos_mar', 'kg', 1, 39.9, 95, 1),
  ('Camarão limpo', array['camarao','camarão','camarão descascado','camarão cinza']::text[], 'peixes_frutos_mar', 'kg', 1, 69.9, 90, 1),
  ('Camarão com casca', array['camarão inteiro','camarão VG']::text[], 'peixes_frutos_mar', 'kg', 1, 49.9, 55, 1),
  ('Bacalhau dessalgado', array['bacalhau','lascas de bacalhau']::text[], 'peixes_frutos_mar', 'kg', 1, 89.9, 85, 1),
  ('Lula limpa', array['lula','anéis de lula']::text[], 'peixes_frutos_mar', 'kg', 1, 44.9, 85, 1),
  ('Polvo', array[]::text[], 'peixes_frutos_mar', 'kg', 1, 89.9, 60, 1),
  ('Atum fresco', array['atum','lombo de atum']::text[], 'peixes_frutos_mar', 'kg', 1, 84.9, 85, 1),
  ('Atum em lata', array['atum enlatado','atum ralado']::text[], 'peixes_frutos_mar', 'g', 170, 7.9, 100, 1),
  ('Sardinha fresca', array['sardinha']::text[], 'peixes_frutos_mar', 'kg', 1, 16.9, 60, 1),
  ('Mexilhão', array['marisco','mexilhao']::text[], 'peixes_frutos_mar', 'kg', 1, 34.9, 70, 1),
  ('Kani', array['kani kama','kanikama','bastão de caranguejo']::text[], 'japonesa', 'kg', 1, 36.9, 100, 1),
  ('Pescada branca filé', array['pescada','filé de pescada','merluza']::text[], 'peixes_frutos_mar', 'kg', 1, 32.9, 95, 1),
  ('Queijo mussarela', array['mussarela','muçarela','mozzarella']::text[], 'laticinios', 'kg', 1, 39.9, 100, 1),
  ('Queijo prato', array['prato fatiado']::text[], 'laticinios', 'kg', 1, 42.9, 100, 1),
  ('Queijo parmesão', array['parmesao','parmesão ralado','grana']::text[], 'laticinios', 'kg', 1, 69.9, 100, 1),
  ('Queijo coalho', array['coalho']::text[], 'laticinios', 'kg', 1, 44.9, 100, 1),
  ('Queijo minas frescal', array['minas frescal','queijo branco']::text[], 'laticinios', 'kg', 1, 36.9, 100, 1),
  ('Queijo cheddar', array['cheddar','cheddar fatiado']::text[], 'laticinios', 'kg', 1, 49.9, 100, 1),
  ('Queijo gorgonzola', array['gorgonzola']::text[], 'laticinios', 'kg', 1, 79.9, 100, 1),
  ('Queijo provolone', array['provolone']::text[], 'laticinios', 'kg', 1, 59.9, 100, 1),
  ('Queijo cream cheese', array['cream cheese','cremoso']::text[], 'laticinios', 'kg', 1, 39.9, 100, 1),
  ('Requeijão', array['requeijao','requeijão cremoso']::text[], 'laticinios', 'kg', 1, 29.9, 100, 1),
  ('Catupiry', array['catupiry original']::text[], 'laticinios', 'kg', 1, 39.9, 100, 1),
  ('Manteiga', array['manteiga com sal','manteiga sem sal']::text[], 'laticinios', 'kg', 1, 49.9, 100, 1),
  ('Margarina', array[]::text[], 'laticinios', 'kg', 1, 12.9, 100, 1),
  ('Creme de leite', array['creme de leite fresco']::text[], 'laticinios', 'L', 1, 15.9, 100, 1),
  ('Creme de leite caixinha', array['creme de leite UHT']::text[], 'laticinios', 'g', 200, 3.4, 100, 1),
  ('Leite integral', array['leite','leite UHT']::text[], 'laticinios', 'L', 1, 5.2, 100, 1),
  ('Leite condensado', array[]::text[], 'laticinios', 'g', 395, 6.9, 100, 1),
  ('Iogurte natural', array['iogurte']::text[], 'laticinios', 'g', 170, 3.2, 100, 1),
  ('Leite em pó', array['leite po']::text[], 'laticinios', 'g', 400, 17.9, 100, 1),
  ('Ovo', array['ovos','ovo branco','dúzia de ovos']::text[], 'ovos', 'un', 30, 19.9, 88, 1),
  ('Ovo de codorna', array['codorna']::text[], 'ovos', 'un', 30, 12.9, 85, 1),
  ('Batata inglesa', array['batata','batata lavada']::text[], 'hortifruti', 'kg', 1, 5.9, 80, 1),
  ('Batata doce', array['batata-doce']::text[], 'hortifruti', 'kg', 1, 5.9, 85, 1),
  ('Batata palito congelada', array['batata frita congelada','batata pré-frita','batata congelada']::text[], 'hortifruti', 'kg', 1, 14.9, 100, 1),
  ('Mandioca', array['aipim','macaxeira']::text[], 'hortifruti', 'kg', 1, 5.9, 70, 1),
  ('Cebola', array['cebola branca']::text[], 'hortifruti', 'kg', 1, 5.4, 85, 1),
  ('Cebola roxa', array[]::text[], 'hortifruti', 'kg', 1, 8.9, 85, 1),
  ('Alho', array['alho descascado','dente de alho']::text[], 'hortifruti', 'kg', 1, 29.9, 85, 1),
  ('Tomate', array['tomate italiano','tomate salada']::text[], 'hortifruti', 'kg', 1, 7.9, 90, 1),
  ('Tomate cereja', array['tomate grape','tomatinho']::text[], 'hortifruti', 'kg', 1, 16.9, 95, 1),
  ('Alface americana', array['alface','alface crespa']::text[], 'hortifruti', 'un', 1, 3.9, 80, 1),
  ('Rúcula', array['rucula']::text[], 'hortifruti', 'un', 1, 3.5, 85, 1),
  ('Cenoura', array[]::text[], 'hortifruti', 'kg', 1, 5.9, 85, 1),
  ('Abobrinha', array[]::text[], 'hortifruti', 'kg', 1, 6.9, 90, 1),
  ('Berinjela', array[]::text[], 'hortifruti', 'kg', 1, 7.9, 90, 1),
  ('Pimentão verde', array['pimentão','pimentao']::text[], 'hortifruti', 'kg', 1, 8.9, 82, 1),
  ('Pimentão vermelho', array[]::text[], 'hortifruti', 'kg', 1, 14.9, 82, 1),
  ('Brócolis', array['brocolis','brócolis ninja']::text[], 'hortifruti', 'un', 1, 7.9, 70, 1),
  ('Couve-flor', array['couve flor']::text[], 'hortifruti', 'un', 1, 8.9, 70, 1),
  ('Couve', array['couve manteiga']::text[], 'hortifruti', 'un', 1, 3.5, 80, 1),
  ('Repolho', array['repolho verde']::text[], 'hortifruti', 'kg', 1, 4.9, 85, 1),
  ('Espinafre', array[]::text[], 'hortifruti', 'un', 1, 4.5, 80, 1),
  ('Abóbora cabotiá', array['abóbora','abobora','cabotiá','jerimum']::text[], 'hortifruti', 'kg', 1, 5.9, 75, 1),
  ('Chuchu', array[]::text[], 'hortifruti', 'kg', 1, 4.9, 80, 1),
  ('Pepino', array['pepino japonês']::text[], 'hortifruti', 'kg', 1, 6.9, 90, 1),
  ('Beterraba', array[]::text[], 'hortifruti', 'kg', 1, 5.9, 80, 1),
  ('Milho verde', array['milho','espiga de milho']::text[], 'hortifruti', 'un', 1, 2.5, 55, 1),
  ('Milho em conserva', array['milho enlatado','milho lata']::text[], 'molhos_conservas', 'g', 170, 3.9, 100, 1),
  ('Cogumelo paris', array['champignon fresco','cogumelo']::text[], 'hortifruti', 'kg', 1, 32.9, 95, 1),
  ('Champignon em conserva', array['champignon','cogumelo em conserva']::text[], 'molhos_conservas', 'g', 200, 7.9, 100, 1),
  ('Limão taiti', array['limão','limao']::text[], 'hortifruti', 'kg', 1, 6.9, 45, 1),
  ('Limão siciliano', array[]::text[], 'hortifruti', 'kg', 1, 12.9, 45, 1),
  ('Laranja', array['laranja pera']::text[], 'hortifruti', 'kg', 1, 4.9, 50, 1),
  ('Banana prata', array['banana']::text[], 'hortifruti', 'kg', 1, 6.9, 65, 1),
  ('Maçã', array['maca','maçã fuji']::text[], 'hortifruti', 'kg', 1, 9.9, 85, 1),
  ('Abacaxi', array[]::text[], 'hortifruti', 'un', 1, 7.9, 55, 1),
  ('Manga', array['manga palmer','manga tommy']::text[], 'hortifruti', 'kg', 1, 7.9, 65, 1),
  ('Morango', array[]::text[], 'hortifruti', 'kg', 1, 24.9, 90, 1),
  ('Melancia', array[]::text[], 'hortifruti', 'kg', 1, 3.9, 55, 1),
  ('Mamão papaya', array['mamão','mamao']::text[], 'hortifruti', 'kg', 1, 6.9, 65, 1),
  ('Abacate', array[]::text[], 'hortifruti', 'kg', 1, 8.9, 70, 1),
  ('Maracujá', array['maracuja']::text[], 'hortifruti', 'kg', 1, 12.9, 40, 1),
  ('Coco ralado', array['coco seco ralado']::text[], 'doces_confeitaria', 'g', 100, 4.9, 100, 1),
  ('Salsinha', array['salsa','cheiro verde']::text[], 'hortifruti', 'un', 1, 2.5, 70, 1),
  ('Cebolinha', array[]::text[], 'hortifruti', 'un', 1, 2.5, 75, 1),
  ('Coentro', array[]::text[], 'hortifruti', 'un', 1, 2.5, 70, 1),
  ('Manjericão', array['manjericao','basílico']::text[], 'hortifruti', 'un', 1, 3.9, 70, 1),
  ('Hortelã', array['hortela']::text[], 'hortifruti', 'un', 1, 3, 70, 1),
  ('Gengibre', array[]::text[], 'hortifruti', 'kg', 1, 19.9, 80, 1),
  ('Pimenta dedo-de-moça', array['pimenta dedo de moça','pimenta vermelha']::text[], 'hortifruti', 'kg', 1, 24.9, 85, 1),
  ('Ervilha congelada', array['ervilha']::text[], 'hortifruti', 'kg', 1, 12.9, 100, 1),
  ('Mix de legumes congelado', array['legumes congelados','jardineira']::text[], 'hortifruti', 'kg', 1, 11.9, 100, 1),
  ('Arroz branco', array['arroz','arroz agulhinha','arroz tipo 1']::text[], 'graos_cereais', 'kg', 5, 24.9, 100, 3),
  ('Arroz integral', array[]::text[], 'graos_cereais', 'kg', 1, 7.9, 100, 2.8),
  ('Arroz arbóreo', array['arroz arboreo','arroz para risoto']::text[], 'graos_cereais', 'kg', 1, 16.9, 100, 3),
  ('Arroz japonês', array['arroz para sushi','shari','arroz japones']::text[], 'japonesa', 'kg', 5, 44.9, 100, 2.5),
  ('Feijão preto', array['feijao preto','feijão']::text[], 'graos_cereais', 'kg', 1, 8.9, 100, 2.5),
  ('Feijão carioca', array['feijao carioca']::text[], 'graos_cereais', 'kg', 1, 8.4, 100, 2.5),
  ('Grão-de-bico', array['grão de bico','grao de bico']::text[], 'graos_cereais', 'kg', 1, 14.9, 100, 2.3),
  ('Lentilha', array[]::text[], 'graos_cereais', 'kg', 1, 11.9, 100, 2.3),
  ('Quinoa', array[]::text[], 'graos_cereais', 'kg', 1, 39.9, 100, 3),
  ('Aveia em flocos', array['aveia']::text[], 'graos_cereais', 'kg', 1, 11.9, 100, 1),
  ('Farinha de trigo', array['farinha','trigo']::text[], 'massas_farinhas', 'kg', 1, 4.9, 100, 1),
  ('Farinha de trigo 00', array['farinha 00','farinha para pizza']::text[], 'massas_farinhas', 'kg', 1, 8.9, 100, 1),
  ('Farinha de mandioca', array['farinha de mandioca torrada']::text[], 'massas_farinhas', 'kg', 1, 7.9, 100, 1),
  ('Farinha de rosca', array['farinha de rosca','panko']::text[], 'massas_farinhas', 'kg', 1, 9.9, 100, 1),
  ('Amido de milho', array['maisena','maizena']::text[], 'massas_farinhas', 'kg', 1, 9.9, 100, 1),
  ('Fubá', array['fuba','farinha de milho']::text[], 'massas_farinhas', 'kg', 1, 5.9, 100, 1),
  ('Polvilho azedo', array['polvilho']::text[], 'massas_farinhas', 'kg', 1, 9.9, 100, 1),
  ('Macarrão espaguete', array['espaguete','macarrão','macarrao','spaghetti']::text[], 'massas_farinhas', 'kg', 1, 7.9, 100, 2.3),
  ('Macarrão penne', array['penne']::text[], 'massas_farinhas', 'kg', 1, 7.9, 100, 2.3),
  ('Massa de lasanha', array['lasanha pré-cozida','massa para lasanha']::text[], 'massas_farinhas', 'kg', 1, 14.9, 100, 1.8),
  ('Macarrão para yakisoba', array['macarrão yakisoba','lámen','lamen']::text[], 'chinesa', 'kg', 1, 12.9, 100, 1.5),
  ('Massa de pastel', array['disco de pastel','massa pastel']::text[], 'massas_farinhas', 'kg', 1, 16.9, 100, 1),
  ('Massa folhada', array[]::text[], 'massas_farinhas', 'kg', 1, 24.9, 100, 1),
  ('Massa de pizza pré-assada', array['disco de pizza','massa de pizza']::text[], 'massas_farinhas', 'un', 1, 6.9, 100, 1),
  ('Pão de forma', array['pao de forma']::text[], 'paes_padaria', 'un', 1, 8.9, 100, 1),
  ('Pão francês', array['pao frances','pão de sal']::text[], 'paes_padaria', 'kg', 1, 16.9, 100, 1),
  ('Pão de hambúrguer', array['pão brioche','pao de hamburguer','pão de burger']::text[], 'paes_padaria', 'un', 1, 1.4, 100, 1),
  ('Pão de hot dog', array['pão de cachorro quente']::text[], 'paes_padaria', 'un', 1, 0.9, 100, 1),
  ('Pão sírio', array['pao sirio','pita']::text[], 'arabe', 'un', 1, 1.5, 100, 1),
  ('Tortilha de trigo', array['tortilla','wrap','rap10']::text[], 'mexicana', 'un', 1, 1.3, 100, 1),
  ('Fermento biológico seco', array['fermento','fermento de pão']::text[], 'massas_farinhas', 'g', 500, 29.9, 100, 1),
  ('Fermento químico', array['fermento em pó','pó royal']::text[], 'doces_confeitaria', 'g', 250, 8.9, 100, 1),
  ('Açúcar refinado', array['açúcar','acucar','açúcar branco']::text[], 'doces_confeitaria', 'kg', 1, 4.4, 100, 1),
  ('Açúcar cristal', array['acucar cristal']::text[], 'doces_confeitaria', 'kg', 1, 4, 100, 1),
  ('Açúcar demerara', array['demerara']::text[], 'doces_confeitaria', 'kg', 1, 8.9, 100, 1),
  ('Sal refinado', array['sal','sal de cozinha']::text[], 'temperos_condimentos', 'kg', 1, 2.5, 100, 1),
  ('Sal grosso', array[]::text[], 'temperos_condimentos', 'kg', 1, 2.9, 100, 1),
  ('Óleo de soja', array['óleo','oleo','óleo de cozinha']::text[], 'oleos_gorduras', 'ml', 900, 7.9, 100, 1),
  ('Azeite de oliva extra virgem', array['azeite','azeite extravirgem']::text[], 'oleos_gorduras', 'ml', 500, 34.9, 100, 1),
  ('Óleo de girassol', array[]::text[], 'oleos_gorduras', 'ml', 900, 9.9, 100, 1),
  ('Gordura vegetal para fritura', array['gordura hidrogenada','gordura de fritura']::text[], 'oleos_gorduras', 'kg', 1, 12.9, 100, 1),
  ('Banha de porco', array['banha']::text[], 'oleos_gorduras', 'kg', 1, 14.9, 100, 1),
  ('Óleo de gergelim', array['oleo de gergelim']::text[], 'japonesa', 'ml', 200, 19.9, 100, 1),
  ('Pimenta-do-reino moída', array['pimenta do reino','pimenta preta']::text[], 'temperos_condimentos', 'g', 500, 34.9, 100, 1),
  ('Páprica defumada', array['paprica','páprica']::text[], 'temperos_condimentos', 'g', 500, 29.9, 100, 1),
  ('Orégano', array['oregano']::text[], 'temperos_condimentos', 'g', 500, 24.9, 100, 1),
  ('Cominho', array[]::text[], 'temperos_condimentos', 'g', 500, 24.9, 100, 1),
  ('Colorau', array['colorífico','urucum']::text[], 'temperos_condimentos', 'g', 500, 9.9, 100, 1),
  ('Louro', array['folha de louro']::text[], 'temperos_condimentos', 'g', 100, 9.9, 100, 1),
  ('Canela em pó', array['canela']::text[], 'doces_confeitaria', 'g', 500, 34.9, 100, 1),
  ('Curry', array[]::text[], 'temperos_condimentos', 'g', 500, 29.9, 100, 1),
  ('Chimichurri', array[]::text[], 'temperos_condimentos', 'g', 500, 24.9, 100, 1),
  ('Tempero pronto', array['tempero completo','sazón','caldo em pó']::text[], 'temperos_condimentos', 'kg', 1, 12.9, 100, 1),
  ('Caldo de carne em tablete', array['caldo knorr','tablete de caldo']::text[], 'temperos_condimentos', 'un', 1, 0.5, 100, 1),
  ('Vinagre de álcool', array['vinagre']::text[], 'temperos_condimentos', 'ml', 750, 3.9, 100, 1),
  ('Vinagre balsâmico', array['balsamico']::text[], 'temperos_condimentos', 'ml', 500, 19.9, 100, 1),
  ('Mostarda', array[]::text[], 'molhos_conservas', 'kg', 1, 14.9, 100, 1),
  ('Ketchup', array['catchup']::text[], 'molhos_conservas', 'kg', 1, 13.9, 100, 1),
  ('Maionese', array[]::text[], 'molhos_conservas', 'kg', 1, 15.9, 100, 1),
  ('Molho de tomate', array['molho de tomate pronto','polpa de tomate','passata']::text[], 'molhos_conservas', 'kg', 1, 8.9, 100, 1),
  ('Extrato de tomate', array[]::text[], 'molhos_conservas', 'g', 340, 4.9, 100, 1),
  ('Molho shoyu', array['shoyu','molho de soja']::text[], 'japonesa', 'ml', 900, 9.9, 100, 1),
  ('Molho inglês', array['molho ingles','worcestershire']::text[], 'molhos_conservas', 'ml', 150, 4.9, 100, 1),
  ('Molho barbecue', array['barbecue','bbq']::text[], 'molhos_conservas', 'kg', 1, 24.9, 100, 1),
  ('Molho de pimenta', array['tabasco','pimenta líquida']::text[], 'molhos_conservas', 'ml', 150, 6.9, 100, 1),
  ('Azeitona verde', array['azeitona','azeitona sem caroço']::text[], 'molhos_conservas', 'kg', 1, 24.9, 100, 1),
  ('Azeitona preta', array[]::text[], 'molhos_conservas', 'kg', 1, 29.9, 100, 1),
  ('Palmito em conserva', array['palmito']::text[], 'molhos_conservas', 'g', 300, 14.9, 100, 1),
  ('Pepino em conserva', array['picles','pickles']::text[], 'molhos_conservas', 'g', 300, 9.9, 100, 1),
  ('Tahine', array['tahini','pasta de gergelim']::text[], 'arabe', 'g', 500, 29.9, 100, 1),
  ('Grão-de-bico cozido (homus base)', array['homus','hummus']::text[], 'arabe', 'kg', 1, 19.9, 100, 1),
  ('Feijão preto refogado (base mexicana)', array['refried beans','feijão refogado']::text[], 'mexicana', 'kg', 1, 16.9, 100, 1),
  ('Jalapeño em conserva', array['jalapeno','pimenta jalapeño']::text[], 'mexicana', 'g', 300, 12.9, 100, 1),
  ('Guacamole base (abacate)', array['guacamole']::text[], 'mexicana', 'kg', 1, 29.9, 100, 1),
  ('Molho teriyaki', array['teriyaki','tarê','tare']::text[], 'japonesa', 'ml', 500, 16.9, 100, 1),
  ('Molho agridoce', array['agridoce']::text[], 'chinesa', 'ml', 500, 12.9, 100, 1),
  ('Óleo de pimenta / chili oil', array['chili oil','óleo de pimenta']::text[], 'chinesa', 'ml', 200, 14.9, 100, 1),
  ('Alga nori', array['nori','folha de alga']::text[], 'japonesa', 'un', 50, 39.9, 100, 1),
  ('Gergelim', array['gergelim branco','gergelim torrado']::text[], 'japonesa', 'kg', 1, 24.9, 100, 1),
  ('Vinagre de arroz', array['su','tempero para sushi']::text[], 'japonesa', 'ml', 500, 14.9, 100, 1),
  ('Wasabi em pasta', array['wasabi']::text[], 'japonesa', 'g', 43, 9.9, 100, 1),
  ('Gengibre em conserva', array['gari','gengibre para sushi']::text[], 'japonesa', 'kg', 1, 29.9, 100, 1),
  ('Hashi descartável', array['hashi']::text[], 'descartaveis', 'un', 100, 24.9, 100, 1),
  ('Missô', array['misso','pasta de soja']::text[], 'japonesa', 'kg', 1, 34.9, 100, 1),
  ('Hondashi', array['dashi','caldo de peixe']::text[], 'japonesa', 'g', 100, 14.9, 100, 1),
  ('Chocolate ao leite em barra', array['chocolate','chocolate ao leite']::text[], 'doces_confeitaria', 'kg', 1, 44.9, 100, 1),
  ('Chocolate meio amargo', array['chocolate 50%','meio amargo']::text[], 'doces_confeitaria', 'kg', 1, 49.9, 100, 1),
  ('Chocolate em pó', array['cacau em pó','achocolatado']::text[], 'doces_confeitaria', 'kg', 1, 24.9, 100, 1),
  ('Granulado de chocolate', array['granulado']::text[], 'doces_confeitaria', 'kg', 1, 19.9, 100, 1),
  ('Doce de leite', array[]::text[], 'doces_confeitaria', 'kg', 1, 19.9, 100, 1),
  ('Goiabada', array[]::text[], 'doces_confeitaria', 'kg', 1, 12.9, 100, 1),
  ('Mel', array[]::text[], 'doces_confeitaria', 'kg', 1, 39.9, 100, 1),
  ('Gelatina em pó', array['gelatina']::text[], 'doces_confeitaria', 'g', 85, 2.9, 100, 1),
  ('Chantilly', array['chantili','creme para chantilly']::text[], 'doces_confeitaria', 'L', 1, 19.9, 100, 1),
  ('Sorvete de creme', array['sorvete']::text[], 'doces_confeitaria', 'L', 5, 59.9, 100, 1),
  ('Polpa de açaí', array['açaí','acai','açaí congelado']::text[], 'doces_confeitaria', 'kg', 1, 24.9, 100, 1),
  ('Polpa de fruta congelada', array['polpa de fruta','polpa']::text[], 'bebidas', 'g', 100, 1.6, 100, 1),
  ('Leite de coco', array[]::text[], 'doces_confeitaria', 'ml', 200, 3.9, 100, 1),
  ('Paçoca', array['pacoca']::text[], 'doces_confeitaria', 'un', 1, 0.6, 100, 1),
  ('Nutella / creme de avelã', array['nutella','creme de avelã']::text[], 'doces_confeitaria', 'g', 650, 34.9, 100, 1),
  ('Refrigerante lata', array['coca lata','refrigerante 350ml','coca-cola lata']::text[], 'bebidas', 'un', 12, 42.9, 100, 1),
  ('Refrigerante 2L', array['coca 2l','refrigerante 2 litros']::text[], 'bebidas', 'un', 1, 9.9, 100, 1),
  ('Água mineral 500ml', array['água','agua mineral','água sem gás']::text[], 'bebidas', 'un', 12, 14.9, 100, 1),
  ('Água com gás 500ml', array['água com gás']::text[], 'bebidas', 'un', 12, 19.9, 100, 1),
  ('Cerveja long neck', array['long neck','heineken long neck','cerveja 330ml']::text[], 'bebidas', 'un', 24, 119.9, 100, 1),
  ('Cerveja lata 350ml', array['cerveja lata','brahma lata']::text[], 'bebidas', 'un', 12, 42.9, 100, 1),
  ('Chope (barril 30L)', array['chope','chopp','barril de chope']::text[], 'bebidas', 'L', 30, 349, 100, 1),
  ('Suco de laranja natural (laranja)', array['suco de laranja']::text[], 'bebidas', 'L', 1, 8.9, 100, 1),
  ('Suco de caixinha 1L', array['suco de caixa','suco pronto']::text[], 'bebidas', 'L', 1, 6.9, 100, 1),
  ('Energético 250ml', array['red bull','energético']::text[], 'bebidas', 'un', 1, 7.9, 100, 1),
  ('Café em grãos', array['café','cafe','café torrado']::text[], 'bebidas', 'kg', 1, 49.9, 100, 1),
  ('Café em pó', array['café moído','pó de café']::text[], 'bebidas', 'kg', 1, 32.9, 100, 1),
  ('Cachaça', array['cachaca','pinga']::text[], 'bebidas', 'ml', 1000, 29.9, 100, 1),
  ('Vodka', array[]::text[], 'bebidas', 'ml', 1000, 49.9, 100, 1),
  ('Gin', array[]::text[], 'bebidas', 'ml', 750, 89.9, 100, 1),
  ('Whisky 8 anos', array['whisky','uísque','red label']::text[], 'bebidas', 'ml', 1000, 119.9, 100, 1),
  ('Vinho tinto de mesa', array['vinho','vinho tinto']::text[], 'bebidas', 'ml', 750, 34.9, 100, 1),
  ('Água tônica', array['tônica','tonica']::text[], 'bebidas', 'un', 6, 19.9, 100, 1),
  ('Gelo em cubos', array['gelo','saco de gelo']::text[], 'bebidas', 'kg', 5, 14.9, 100, 1),
  ('Caldo de cana (cana)', array['cana de açúcar','cana']::text[], 'bebidas', 'kg', 1, 2.5, 55, 1),
  ('Marmitex alumínio nº 8', array['marmitex','quentinha','marmita de alumínio']::text[], 'embalagens', 'un', 100, 79.9, 100, 1),
  ('Marmita isopor 750ml', array['marmita isopor','embalagem isopor']::text[], 'embalagens', 'un', 100, 69.9, 100, 1),
  ('Pote plástico 500ml com tampa', array['pote 500ml','pote plástico']::text[], 'embalagens', 'un', 100, 59.9, 100, 1),
  ('Caixa de pizza 35cm', array['caixa de pizza','embalagem pizza']::text[], 'embalagens', 'un', 50, 89.9, 100, 1),
  ('Embalagem de hambúrguer', array['caixa de hambúrguer','box burger']::text[], 'embalagens', 'un', 100, 54.9, 100, 1),
  ('Embalagem para batata frita', array['cone de batata','saco de batata']::text[], 'embalagens', 'un', 100, 39.9, 100, 1),
  ('Copo plástico 300ml', array['copo descartável','copo 300ml']::text[], 'descartaveis', 'un', 100, 12.9, 100, 1),
  ('Copo para açaí 500ml com tampa', array['copo açaí','copo 500ml']::text[], 'embalagens', 'un', 100, 69.9, 100, 1),
  ('Sacola plástica delivery', array['sacola','sacola plástica']::text[], 'embalagens', 'un', 100, 24.9, 100, 1),
  ('Saco de papel kraft', array['saco kraft','sacola kraft']::text[], 'embalagens', 'un', 100, 49.9, 100, 1),
  ('Talher descartável kit', array['kit talher','talheres descartáveis']::text[], 'descartaveis', 'un', 100, 39.9, 100, 1),
  ('Guardanapo', array['guardanapo de papel']::text[], 'descartaveis', 'un', 1000, 24.9, 100, 1),
  ('Papel alumínio', array[]::text[], 'descartaveis', 'm2', 15, 9.9, 100, 1),
  ('Filme plástico PVC', array['plástico filme','filme pvc']::text[], 'descartaveis', 'm2', 30, 12.9, 100, 1),
  ('Canudo', array['canudo de papel']::text[], 'descartaveis', 'un', 200, 14.9, 100, 1),
  ('Lacre de segurança para delivery', array['lacre','etiqueta lacre']::text[], 'embalagens', 'un', 500, 34.9, 100, 1),
  ('Embalagem de sushi (bandeja)', array['bandeja de sushi','embalagem sushi']::text[], 'embalagens', 'un', 50, 69.9, 100, 1),
  ('Embalagem para pastel', array['saco de pastel']::text[], 'embalagens', 'un', 500, 29.9, 100, 1)
) as v(nome, sinonimos, categoria, unidade_compra, qtd_padrao, preco_medio, fator_aproveitamento, rendimento_preparo)
on conflict (lower(nome), regiao) do nothing;

insert into public.catalogo_precos_historico (catalogo_id, preco, origem)
select c.id, c.preco_medio, 'estimativa inicial' from public.catalogo_base c
where not exists (select 1 from public.catalogo_precos_historico h where h.catalogo_id = c.id);
